-- 한글 1글자 = 3BYTE / 영어 1글자 = 1BYTE
CREATE TABLE TEST_TBL (
	MEM_NO INT(5),
	MEM_NAME VARCHAR(50) NOT NULL,
	MEM_AGE INT(3) NOT NULL,
	MEM_GENDER ENUM('M','F'),
	MEM_SIGNIN_DATE DATETIME NOT NULL,
	MEM_SIGNOUT_DATE DATETIME,
	CONSTRAINT PK_EMPLOYEES_MEM_NO PRIMARY KEY(MEM_NO)
);

-- DB 컬럼 추가
ALTER TABLE test_tbl ADD COLUMN ADDR1 VARCHAR(300);

SELECT * FROM test_tbl;

SHOW FULL COLUMNS FROM test_tbl;

-- DB 컬럼 변경
ALTER TABLE test_tbl ALTER COLUMN ADDR1 VARCHAR(200);

-- DB 컬럼 삭제
ALTER TABLE test_tbl DROP COLUMN ADDR1;

INSERT INTO test_tbl (
MEM_NO,
MEM_NAME,
MEM_AGE,
MEM_GENDER,
MEM_SIGNIN_DATE,
MEM_SIGNOUT_DATE
) VALUES (
2,
'채수지',
21,
'F',
NOW(),
NULL
);

COMMIT;

SELECT * FROM test_tbl;

DELETE FROM test_tbl;

ROLLBACK;

-- TRUNCATE, DROP = 복구 불가 
TRUNCATE TABLE test_tbl;

DROP TABLE test_tbl;